---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-postgres-secrets
  namespace: n8n
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBImZxnx8XWMVuSusJvqnc5KEdEZdvcyrzMb/3OtQZu9kxPVkCR60TBf0xvLLs5dSSW3AdH+8DsFjlYn+Euef+8Zb9c1R1jSKMoD5shYRVvecUcUpWUaDR+lbSQYx2rtJcJPhZVjOovET1EN5SMLm9RalozizjtgpzLYfflLLDfjX+wDF7rjKi9k4pzJSa/nk0KUNilMQ+f76/910oDtpvwNazi++w4PCLeWN4Xprfy4hkH27CcWttefsUNjxKAxPukhJNrYiA6X2mJ7hfE2Och4X512uBvqTFxXgi7N5pxHk2mjsyjeHoTle4wafFlSg/iruloIJlH2dEIvesZiIhbylClVBQpPvWwUQhh3MBiDffZNWT1r1JoLbciVGJ9+HiAJirrBilMuQFuBLWOqOoC4LqTkKARMgw1bhvx2Nry5Xf9CE5BYlym8sJOuXgFC45Xo6hTYebWWqJjQuY3L7psV9efEp7jhRURdQSxc2wPs4AK/gJBE7C9Y7Q7smUYn3ZgiNAeZ0Fcs8XHUXC+ERVaSio8z7CiUEgfOoNcWarghfbFrM6/1VMNgtRUcK7tmrVV6wERJr0WzqCzO+zXvjf4OECKn9dU8J2GxSiHk9iODOEERgOADSEJ/efNCOunwSqN4HM67ggG5tW5UofFr50730VKr/RmznMZBqFMbVG85CT1YPykRXD5++WXGtrkN/WvUMsT5Auga2g=
  template:
    metadata:
      name: n8n-postgres-secrets
      namespace: n8n
