apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-livekit
  namespace: churaverse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-livekit
  template:
    metadata:
      labels:
        app: backend-livekit
    spec:
      containers:
        - name: backend-livekit
          image: harbor.youkan.uk/churaverse/backend_livekit:0.0.6
          ports:
            - containerPort: 12150
              name: http
          env:
            - name: NODE_ENV
              value: development
            - name: ALLOW_ORIGIN
              value: https://churaverse.youkan.uk
            - name: LIVEKIT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: churaverse-secrets
                  key: LIVEKIT_API_KEY
            - name: LIVEKIT_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: churaverse-secrets
                  key: LIVEKIT_API_SECRET
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
