apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: churaverse
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 3000
      targetPort: http
