apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: churaverse

resources:
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-livekit-deployment.yaml
  - backend-livekit-service.yaml
  - ingress.yaml
  - churaverse-secrets.enc.yaml

helmCharts:
  - name: livekit-server
    repo: https://helm.livekit.io
    version: 1.5.0
    releaseName: livekit
    namespace: churaverse
    valuesInline:
      livekit:
        port: 7880
        key_file: /etc/livekit/keys.yaml
        rtc:
          tcp_port: 7881
          port_range_start: 50000
          port_range_end: 60000
          use_external_ip: true
      storeKeysInSecret:
        enabled: true
        existingSecret: "churaverse-secrets"
