apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
spec:
  project: default
  sources:
    # Sealed Secret の管理
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: apps/dashy
    # Helm chart の管理
    - repoURL: https://vyrtualsynthese.github.io/selfhosted-helmcharts/
      chart: dashy
      targetRevision: "1.0.0"
      helm:
        releaseName: dashy
        valuesObject:
          replicaCount: 1
          
          # イメージ設定
          image:
            repository: lissy93/dashy
            tag: latest
            pullPolicy: IfNotPresent
          
          # サービス設定
          service:
            type: ClusterIP
            port: 8080
          
          # Ingress 設定
          ingress:
            enabled: true
            className: cloudflare
            hosts:
              - host: dashy.youkan.uk
                paths:
                  - path: /
                    pathType: Prefix
          
          # リソース制限
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          
          # 環境変数
          env:
            NODE_ENV: "production"
            PORT: 8080
          
          # ConfigMap で config.yaml を管理
          static:
            enabled: true
            configMapContent:
              conf: |-
                # ページのメタ情報
                pageInfo:
                  title: Home Dashboard
                  description: ホームラボダッシュボード
                
                # アプリケーション設定
                appConfig:
                  theme: nord
                  language: ja
                
                # セクション定義
                sections:
                  - name: 家庭サーバー
                    icon: fas fa-home
                    items:
                      - title: Grafana
                        description: メトリクス・ダッシュボード
                        url: https://grafana.youkan.uk
                        icon: fas fa-chart-line
                      - title: Misskey
                        description: フェデレーション型SNS
                        url: https://mi.youkan.uk
                        icon: fas fa-share-nodes
                      - title: Minecraft
                        description: マルチプレイサーバー
                        url: https://mc.youkan.uk
                        icon: fas fa-cube
                  
                  - name: 管理ツール
                    icon: fas fa-tools
                    items:
                      - title: ArgoCD
                        description: GitOps デプロイメント
                        url: https://argocd.youkan.uk
                        icon: fas fa-code-branch
                      - title: Rancher
                        description: Kubernetes マネージャー
                        url: https://rancher.youkan.uk
                        icon: fas fa-ship
                  
                  - name: インフラストラクチャ
                    icon: fas fa-server
                    items:
                      - title: TrueNAS
                        description: ストレージ管理
                        url: https://truenas.youkan.uk
                        icon: fas fa-database
                      - title: MinIO
                        description: オブジェクトストレージ
                        url: http://minio.youkan.uk
                        icon: fas fa-boxes
                      - title: S3
                        description: S3 API
                        url: http://s3.youkan.uk
                        icon: fas fa-cloud
                      - title: File Browser
                        description: ファイルマネージャー
                        url: http://file-browser.youkan.uk
                        icon: fas fa-folder-open
                  
                  - name: ホームオートメーション
                    icon: fas fa-robot
                    items:
                      - title: Home Assistant
                        description: ホームオートメーション
                        url: http://ha.youkan.uk
                        icon: fas fa-lightbulb
                  
                  - name: 物理サーバー
                    icon: fas fa-network-wired
                    items:
                      - title: Mochi (Proxmox)
                        description: ハイパーバイザー
                        url: https://mochi.youkan.uk
                        icon: fas fa-server
                      - title: Aduki (Proxmox)
                        description: ハイパーバイザー
                        url: https://aduki.youkan.uk
                        icon: fas fa-server
                      - title: Anko (Proxmox)
                        description: ハイパーバイザー
                        url: https://anko.youkan.uk
                        icon: fas fa-server
                      - title: Monaka (Proxmox)
                        description: ハイパーバイザー
                        url: https://monaka.youkan.uk
                        icon: fas fa-server
                      - title: iLO (Anko)
                        description: サーバーコンソール
                        url: https://ilo.youkan.uk
                        icon: fas fa-terminal
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dashy
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
