apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fission
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/p-nasimonan/home-manifests.git
    targetRevision: main
    path: apps/fission
    helm:
      skipCrds: false
  destination:
    server: https://kubernetes.default.svc
    namespace: fission
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true