apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    # Helm chart の管理
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.5
      helm:
        releaseName: grafana
        valuesObject: {}
    # Values の管理
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: apps/grafana
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true