apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    # Sealed Secret の管理
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: apps/grafana
    # Helm chart の管理
    - repoURL: https://grafana.github.io/helm-charts
      chart: grafana
      targetRevision: 10.5.5
      helm:
        releaseName: grafana
        valuesObject:
          admin:
            existingSecret: grafana-secrets
            userKey: ADMIN_USER
            passwordKey: ADMIN_PASSWORD
          persistence:
            enabled: true
            size: 10Gi
            storageClassName: nfs-client
          envFromSecret: grafana-secrets
          datasources:
            datasources.yaml:
              apiVersion: 1
              datasources:
              - name: InfluxDB
                type: influxdb
                url: http://192.168.0.31:8086
                database: homeassistant
                user: homeassistant
                secureJsonData:
                  password: $__env{INFLUXDB_PASSWORD}
                isDefault: true
          ingress:
            enabled: true
            ingressClassName: cloudflare
            hosts:
              - grafana.youkan.uk
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true