apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/p-nasimonan/home-manifests.git
    targetRevision: main
    path: apps/minecraft
    helm:
      values: |
        minecraft:
          service:
            type: LoadBalancer
            loadBalancerIP: 192.168.0.220
            port: 25565
          
          # ついでに他の大事な設定もここで保証してしまう
          minecraftServer:
            eula: "TRUE"
            env:
              OPS: "Youkan0124"
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
