apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-postgresql
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 12.12.10
    helm:
      valuesObject:
        global:
          storageClass: nfs-client
        image:
          tag: 16.6.0-debian-12-r3
        auth:
          username: misskey
          database: misskey
          existingSecret: misskey-secrets
          secretKeys:
            adminPasswordKey: POSTGRES_PASSWORD
        primary:
          persistence:
            enabled: true
            size: 20Gi
        fullnameOverride: misskey-postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
