apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-redis
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: redis
      targetRevision: 19.5.2
      helm:
        valueFiles: []
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      path: apps/misskey
      helm:
        valueFiles:
          - redis.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
