apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-postgresql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: postgresql
    targetRevision: 16.4.x 
    helm:
      valuesObject:
        volumePermissions: # 起動前に権限修正
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/os-shell
            tag: latest
        global:
          storageClass: proxmox-data
          security:
            allowInsecureImages: true
        image:
          repository: bitnami/postgresql
          tag: latest
        auth:
          username: misskey
          database: misskey
          existingSecret: misskey-secrets
          secretKeys:
            adminPasswordKey: POSTGRES_PASSWORD
            userPasswordKey: POSTGRES_PASSWORD
        primary:
          persistence:
            enabled: true
            size: 20Gi
            storageClass: proxmox-data
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
        fullnameOverride: misskey-postgresql
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true