apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-postgresql
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: postgresql
      targetRevision: 12.12.10
      helm:
        valueFiles:
          - $values/apps/misskey/postgresql.values.yaml
    - repoURL: https://github.com/p-nasimonan/home-manifests.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
