apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-redis
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.5.2
    helm:
      valuesObject:
        architecture: standalone
        fullnameOverride: misskey-redis
        image:
          registry: public.ecr.aws
          repository: bitnami/redis
          tag: 7.2.4-debian-12-r10
        auth:
          enabled: true
          existingSecret: misskey-secrets
          existingSecretPasswordKey: REDIS_PASSWORD
        master:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: nfs-client
      global:
          storageClass: nfs-client
          security:
            allowInsecureImages: true
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
