apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: misskey-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.5.2
    helm:
      valuesObject:
        architecture: standalone
        global:
          storageClass: proxmox-data
          security:
            allowInsecureImages: true
        image:
          repository: bitnami/redis
          tag: latest
        auth:
          enabled: true
          existingSecret: misskey-secrets
          existingSecretPasswordKey: REDIS_PASSWORD
        master:
          persistence:
            enabled: true
            size: 5Gi
            storageClass: proxmox-data
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          fullnameOverride: misskey-redis
  destination:
    server: https://kubernetes.default.svc
    namespace: misskey
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
