apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubichill
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ubichill/ubichill-backend:latest,frontend=ghcr.io/ubichill/ubichill-frontend:latest,video-player=ghcr.io/ubichill/video-player-backend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: latest
    argocd-image-updater.argoproj.io/frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/video-player.update-strategy: latest
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/video-player.force-update: "true"
spec:
  project: default
  source:
    repoURL: https://ubichill.github.io/ubichill
    targetRevision: 0.1.5
    chart: ubichill
    helm:
      valuesObject:
        global:
          imageRegistry: ""
        backend:
          replicaCount: 1
          autoscaling:
            enabled: false
          env:
            RATE_LIMIT_MAX_REQUESTS: "10000"
            RATE_LIMIT_WINDOW_MS: "900000"
            REDIS_URL: "redis://ubichill-redis-master:6379"
            SESSION_SECRET: "production-session-secret-key"
            NODE_ENV: "production"
            CORS_ORIGIN: "https://ubichill.youkan.uk"
          image:
            repository: ghcr.io/ubichill/ubichill-backend
            tag: latest
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          healthcheck:
            enabled: true
            livenessProbe:
              initialDelaySeconds: 90
              periodSeconds: 45
              timeoutSeconds: 15
              failureThreshold: 6
            readinessProbe:
              initialDelaySeconds: 45
              periodSeconds: 15
              timeoutSeconds: 10
              failureThreshold: 5
        frontend:
          replicaCount: 1
          autoscaling:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2Gi
          env:
            NODE_ENV: "production"
          image:
            repository: ghcr.io/ubichill/ubichill-frontend
            tag: latest
        rooms:
          enabled: true
          custom:
            meeting-room:
              apiVersion: ubichill.com/v1alpha1
              kind: Room
              metadata:
                name: workspace
                version: "1.0.0"
                author:
                  name: "Ubichill Team"
              spec:
                displayName: "ワークスペース"
                description: "落ち着いた雰囲気の作業空間"
                thumbnail: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=200&fit=crop&q=80"
                
                capacity:
                  default: 8
                  max: 15
                
                environment:
                  backgroundColor: "#1a1a2e"
                  backgroundImage: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1920&q=80"
                  worldSize:
                    width: 2000
                    height: 1500
                
                dependencies:
                  - name: pen:pen
                    source:
                      type: repository
                      path: "plugins/pen"
                  - name: video-player
                    source:
                      type: repository
                      path: "plugins/video-player"
                  - name: avatar
                    source:
                      type: repository
                      path: "plugins/avatar"

                initialEntities:
                  - kind: "video-player"
                    transform:
                      x: 800
                      y: 100
                      z: 2
                      w: 800
                      h: 450
                      rotation: 0
                    data:
                      playlist: []
                      currentIndex: 0
                      isPlaying: false
                      volume: 0.7
                      currentTime: 0
                      loop: 'none'
                      shuffle: false
                
                permissions:
                  allowGuestCreate: true
                  allowGuestDelete: false

        redis:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/redis
            tag: latest
        postgresql:
          enabled: false
        ingress:
          enabled: true
          className: cloudflare
          hosts:
            - host: ubichill.youkan.uk
              paths:
                - path: /api
                  pathType: Prefix
                  backend:
                    service:
                      name: backend
                      port:
                        number: 3001
                - path: /socket.io
                  pathType: Prefix
                  backend:
                    service:
                      name: backend
                      port:
                        number: 3001
                - path: /plugin/video-player
                  pathType: Prefix
                  backend:
                    service:
                      name: video-player-backend
                      port:
                        number: 8000
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: frontend
                      port:
                        number: 3000
        video-player:
          enabled: true
          backend:
            replicaCount: 1
            rootPath: "/plugin/video-player"
            autoscaling:
              enabled: false
            image:
              repository: ghcr.io/ubichill/video-player-backend
              tag: latest
            env:
              LOG_LEVEL: INFO
              ROOT_PATH: "/plugin/video-player"
              CORS_ORIGIN: "https://ubichill.youkan.uk"
            resources:
              requests:
                cpu: 500m
                memory: 512Mi
              limits:
                cpu: 2000m
                memory: 3Gi
            healthcheck:
              enabled: true
              livenessProbe:
                initialDelaySeconds: 45
                periodSeconds: 20
                timeoutSeconds: 10
                failureThreshold: 5
              readinessProbe:
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
          redis:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ubichill
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/rollme
        - /spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation
        - /spec/template/spec/containers/0/securityContext/capabilities
        - /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status
