apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ubichill-helm-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ubichill/ubichill-backend:dev,frontend=ghcr.io/ubichill/ubichill-frontend:dev,video-player=ghcr.io/ubichill/video-player-backend:dev
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
    argocd-image-updater.argoproj.io/video-player.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.force-update: "true"
    argocd-image-updater.argoproj.io/frontend.force-update: "true"
    argocd-image-updater.argoproj.io/video-player.force-update: "true"
  labels:
    environment: development
    component: ubichill
spec:
  project: default
  source:
    repoURL: https://github.com/ubichill/ubichill
    targetRevision: feat/helm-deployment  # Use feature branch for testing
    path: charts/ubichill
    helm:
      valueFiles:
        - values-dev.yaml
      valuesObject:
        global:
          imageRegistry: ""
        backend:
          replicaCount: 1
          env:
            RATE_LIMIT_MAX_REQUESTS: "10000"
            RATE_LIMIT_WINDOW_MS: "60000"
            REDIS_URL: "redis://ubichill-helm-dev-redis-master:6379"
            SESSION_SECRET: "dev-session-secret-key"
            NODE_ENV: "production"
            DEBUG: "true"
            CORS_ORIGIN: "https://ubichill-dev.youkan.uk"
          image:
            repository: ghcr.io/ubichill/ubichill-backend
            tag: dev
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          healthcheck:
            enabled: true
            livenessProbe:
              initialDelaySeconds: 90
              periodSeconds: 45
              timeoutSeconds: 15
              failureThreshold: 6
            readinessProbe:
              initialDelaySeconds: 45
              periodSeconds: 15
              timeoutSeconds: 10
              failureThreshold: 5
        frontend:
          env:
            NODE_ENV: "development"
          image:
            repository: ghcr.io/ubichill/ubichill-frontend
            tag: dev
        rooms:
          enabled: true
          custom:
            meeting-room:
              apiVersion: ubichill.com/v1alpha1
              kind: Room
              metadata:
                name: meeting-room
                version: "1.0.0"
              spec:
                displayName: "会議室"
                description: "プレゼンテーション用の部屋"
                environment:
                  backgroundColor: "#2C3E50"
        redis:
          enabled: true
          image:
            registry: docker.io
            repository: bitnami/redis
            tag: latest
        postgresql:
          enabled: false
        ingress:
          enabled: true
          className: cloudflare
          hosts:
            - host: ubichill-dev.youkan.uk
              paths:
                - path: /api
                  pathType: Prefix
                  backend:
                    service:
                      name: backend
                      port:
                        number: 3001
                - path: /socket.io
                  pathType: Prefix
                  backend:
                    service:
                      name: backend
                      port:
                        number: 3001
                - path: /plugin/video-player-api
                  pathType: Prefix
                  backend:
                    service:
                      name: video-player-backend
                      port:
                        number: 8000
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: frontend
                      port:
                        number: 3000
        video-player:
          enabled: true
          backend:
            replicaCount: 1
            autoscaling:
              enabled: false
            image:
              repository: ghcr.io/ubichill/video-player-backend
              tag: dev
            env:
              LOG_LEVEL: DEBUG
            resources:
              requests:
                cpu: 200m
                memory: 256Mi
              limits:
                cpu: 1500m
                memory: 2Gi
            healthcheck:
              enabled: true
              livenessProbe:
                initialDelaySeconds: 45
                periodSeconds: 20
                timeoutSeconds: 10
                failureThreshold: 5
              readinessProbe:
                initialDelaySeconds: 20
                periodSeconds: 10
                timeoutSeconds: 5
                failureThreshold: 3
          redis:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: ubichill-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 5
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/rollme
        - /spec/template/spec/containers/0/securityContext/allowPrivilegeEscalation
        - /spec/template/spec/containers/0/securityContext/capabilities
        - /spec/template/spec/containers/0/securityContext/readOnlyRootFilesystem
    # Ignore HPA changes (managed by auto-scaling)
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /status
  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'Backend'
      value: 'Node.js/TypeScript'
    - name: 'Frontend'
      value: 'Next.js'
    - name: 'Shared Redis'
      value: 'Enabled'