apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: video-player-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/ubichill/video-player-backend:dev
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.force-update: "true"
  labels:
    environment: development
    component: video-player
spec:
  project: default
  source:
    repoURL: https://github.com/ubichill/ubichill
    targetRevision: feat/helm-deployment  # Use specific branch for testing
    path: charts/video-player
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: global.imageRegistry
          value: "ghcr.io/ubichill"
        - name: backend.image.repository
          value: "video-player-backend"
        - name: backend.image.tag
          value: "dev"
        - name: backend.env.LOG_LEVEL
          value: "DEBUG"
        - name: redis.enabled
          value: "false"  # Use shared ubichill Redis instead
  destination:
    server: https://kubernetes.default.svc
    namespace: ubichill-helm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace already exists
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations/rollme
  # Health checks
  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'Redis Cache'
      value: 'Enabled'