apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  source:
    repoURL: https://backube.github.io/helm-charts/
    chart: volsync
    targetRevision: 0.12.1
    helm:
      releaseName: volsync
  destination:
    server: https://kubernetes.default.svc
    namespace: volsync-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
