apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync-backup
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/p-nasimonan/home-manifests.git
    targetRevision: main
    path: apps/volsync-backup
  destination:
    server: https://kubernetes.default.svc
    namespace: volsync-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
