apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vrc-queue-monitor-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: https://github.com/p-nasimonan/home-manifests.git
    targetRevision: main
    path: apps/vrc-queue-monitor
  destination:
    server: https://kubernetes.default.svc
    namespace: vrc-queue-monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
