apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wolweb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/p-nasimonan/home-manifests.git
    targetRevision: HEAD
    path: apps/wolweb
  destination:
    server: https://kubernetes.default.svc
    namespace: wolweb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
