---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: proxmox-csi-config
  namespace: kube-system
spec:
  encryptedData:
    config.yaml: AgCHf9NhlTn5tH9fDtlyB/Zyb1OJgzOz8tmHJV+1KjE3lD/7k/goH0axS7X7z4GXIiZzAIv0UNcA9L4PPS7PZD0WjKTaAHQZ5dc+hCjch0YSng9/h46pR+AEgxjfzJccXrkv9D5jfFRc/5YJYsEkJTbUH3G9wT/70dZgvcqH7tzRVenw0pRVW2wnB6Z0KNJ4ygb4bwxFic30fIQKST15bdoxUPShqQk9XmWYt8mHey/JNdsu7NoSg3H3eGD4EFsePnXmedcBxc7dmblkNJhHyjgX+1vMad5gseO+trxIILkYEvkdM6f8pvyQlNfX1C48NfJZ3mYG2cS385IyBKZVXQqk+5keu48UpXw6O2lw3qnJociIqkQ87UQpocEjXGAYnwLzr2vkOMt/r2645gnRj7kN1us6U/R0xchzPkfkJW32E99jJG0ekNL8SbkN4EJM9UKKolTt3ic4kU49t8PyVKmXpOLg12BRw048vIFY9LLRZ1YaPuZKqUbxCSGxT5d0dlzEE88J4O4O6xwwmt0Wnz+aOvkW9aOBeVe9DUjeckuTj+yC0vluDWSZ7gcVTqfK/vX1LEe0NCo49OU0kGbd5c4lHX5Onf3nwNjIxvPu8olc9tdwnqgcgg37MK7w5VfvmeOnhxiJg1/tEkFKyLJKY7fW9uqz8U9GHdXWASnPnAm/d4RdZwCoKW7b9M0hApkyIrY35Ze8yqQ3LbSdh7rWYvbPHHx3mypmwjlYLC2XA9dohFbwTTO/g52maToflf831NB44Onughkgd2kakfKXXXvfqRHbmuEPLzU1ySz0CbWkYNHLM/fmJLGgCKc+NKKqdGEKWgVuihn8ICelwJkh5XmGxYTps06p/SQZk/3fwJfqRSg4wI84Ls9k9h7YTo1+v4QssL1U1lf8PKK/csfG9a3WYdGIQQGb8BqJ67FAMqM1gP2YnRApKzQ0L8gjCWMv2ncsiHc7/f15+Z/yVfi88xfEK5K1g4BxMmZtBc9/zGOHkY4558mzBQFgV+8AZ/KfZB8A1KzzbTUHrhLzLboWfz/sTwLIDOsAulJnldRXKt7RRfk8/4cRemy3ymEB0qiHkxQE6gCrC+xtPatyOlAOKpovbgFn7jgL8HC9oLorHoXKsqmMYmgDZMAD7s5YjlXlwo0MxTeikFblykjn4A4+jH+E0+emVUfIB2pJgUCMIHKutT9DptO58+XjocI=
  template:
    metadata:
      name: proxmox-csi-config
      namespace: kube-system
