apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashy-data
  namespace: dashy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: proxmox-data
  resources:
    requests:
      storage: 5Gi
