helm:
  parameters:
  - name: frontend.image.tag
    value: latest
    forcestring: true
  - name: backendApi.image.tag
    value: latest
    forcestring: true
  - name: backendCollector.image.tag
    value: latest
    forcestring: true
