apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # rclone config (S3/rustfs - SealedSecret)
  - volsync-rclone-config-misskey.enc.yaml
  - volsync-rclone-config-vrc-queue-monitor.enc.yaml
  - volsync-rclone-config-n8n.enc.yaml

  # ReplicationSources
  - misskey-postgresql.yaml
  - misskey-meilisearch.yaml
  - vrc-queue-monitor-postgresql.yaml
  - n8n.yaml
