---
# misskey: Meilisearch バックアップ
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: misskey-meilisearch-backup
  namespace: misskey
spec:
  sourcePVC: meilisearch-data
  trigger:
    schedule: "30 3 * * *"  # 毎日午前3時30分
  rclone:
    rcloneConfigSection: s3-backup
    rcloneDestPath: k3s/misskey-meilisearch
    copyMethod: Direct
    rcloneConfig: volsync-rclone-config
    moverSecurityContext:
      runAsUser: 0
