---
# misskey: PostgreSQL バックアップ
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: misskey-postgresql-backup
  namespace: misskey
spec:
  sourcePVC: data-misskey-postgresql-0
  trigger:
    schedule: "0 3 * * *"  # 毎日午前3時
  rclone:
    rcloneConfigSection: s3-backup
    rcloneDestPath: k3s/misskey-postgresql
    copyMethod: Direct
    rcloneConfig: volsync-rclone-config
    moverSecurityContext:
      runAsUser: 1001
      fsGroup: 1001
