---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: volsync-rclone-config
  namespace: misskey
spec:
  encryptedData:
    rclone.conf: AgAWi6CEY3tbIURuDcx8hBQ/rxkUhuupdj5CJivFvkcFEbfobMY29TL6ilvB3aMx3JuxfyObLRFUEpIWdCsbBxj88BQ8QSUsADqqHk1LA/uP8NDW3KFM8UkWoBnDmNZs3TKfUDilfES4aw0v65yh7oKOFXtnC/w7tYkZ9/WWIH3iCBJoGTeR3FdKGmObKX77JRduSPyutfFySr0Ujn7LWAZQyrk1LOA6dZ+9QhhSx3qootCRD2v0xP2mQLRGZ1Ah4KDETokNSloI1pevsT6ceW2aZUC5+omQI/iqfek29bofLsPwKBtef9tLPOjF+77lHFU4ZpaPXt1L15vjmspfAbuPuWIRIIWD9+Uir+137aQq48EYZ4MPTHRmfYZH9+qI6RyEaOAOgvzSbMuHka6n/5HdyKA/p7z4gDTo2fg/KBbM5pR5Bkjhunekx5vveOJeCoWQeNwDD3vL8W3v0hRjKH/FUC11bOIdyD2oEb6xpJxWaRb+XqTvLMUw7QDWoXXnJFvcn2J+5OIxrZl93jTb+0QbM6J85jE7QZ0zLikBHuXmqzqqJmZwRh0pBwcD+MeFKKXPLxcsUnfnP3i1eE+XC0SGy4o8kLdEgRKNKKeGHVq1UOHANC6a1UiCVas2lRS9rKpVdWM19PCHX7t82pcTcvsmpUmvQ6PiV0QRjMWX3oxujGbb4k5+WM5Sx/Ee3elNA0E2EKFLXh6ph2W0xTxb+nePEwe1btHiq8is6Uy3h3aNznwg243ortqzA/MXqNpImIT2NXC90dzepBEmfFUrG+uYHYdR74nXVEbeSS0JSI5Pt1GAmcglB8GaeYc1KzVUcHrHZG9g82b6SkT6zARVNnrLlz5LCdVuzEV1+qeB78/teyK2DuDtU28h5s1GAN4ChCX9VzxxFtq3WCZReUU/rfOfAqJ90opwew8Xi35VcVI9rYKtmEDPDrfaS7afztgBChOsoJM=
  template:
    metadata:
      name: volsync-rclone-config
      namespace: misskey
