---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-actions-runner-secrets
  namespace: github-actions
spec:
  encryptedData:
    github_token: AgB1elluDCzZWBnS9iIie7xn6NQ1TJDlF8bZ97sCgU9HUKMylqE4pLkKL9X9Bsb8A+SVEr6cpTeUMPCJu0+qwpwfr5REgzecBx0widpwOafIaBV0/kxkqquoaHR/6YMREqTmWk7qPSCAhdVG5sifnYe+TWIOIvNgTYUUSSydgeVf72BGraG3V38ZHXHzWz62axHqYKvWx6eIbcfXUbz67KcLcw5EbJrBmbOX+uUPnSPCw2jGKE/skWlYc6ear9Y0EYpeidZjXaIF4plwHO81J5h6jKQI9ch3gOqmIZ4aT6j2NAlGLtq5xHNsOP5K4whmsA9/J8SWIRmZvv6hHQGLSctAutc7+Q6TZAe7PtxllrA4+4+jSzc2yyhPN7CXGgGHnZawxUc0ncCNnABRYnCnpFhfKtrj5P3pZR8qOplEyW6/jLk3UiEyZanMFgGQ1Q7yCYElSKJVKFlYZhzx+usQsZojCzhAxCbwoqbcuIUJ/KfsyhKvAllpdx+VOJa5AMP8zIXw3RAkfKVj+GxI9rRZYmCW5pTZWkTbbL+WoKK3tMFyDj/D2gXzXYGdXXAwxQxMlCpQRyrq1FTgZMoF0W1kF7zk7z6KCBNAL1NkJjCyq2K/yHSfxjC6xcCU1tJL/MHAtPA9uFC+C8KjStm6Bv9nwc1tVALEbpQd1QsEYq3xxS6BdNRoYPI1fQzzZvM0bpr6JtYHPs6zUaPii55+cI7AzhNVLEp6w726fdJbq8vpdbjoL6HJ0ZqyTglW
  template:
    metadata:
      name: github-actions-runner-secrets
      namespace: github-actions
