apiVersion: v1
kind: ConfigMap
metadata:
  name: wolweb-config
  namespace: wolweb
data:
  config.json: |
    {
      "host": "0.0.0.0",
      "port": 8089,
      "vdir": "/wolweb",
      "bcastip": "192.168.1.255:9",
      "read_only": false
    }
