---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wolweb-devices
  namespace: wolweb
spec:
  encryptedData:
    devices.json: AgAADkNeqlC0l4Fjl2X59yS3nS/ubIAPzaFK+3pRkSkn6ol8F163Wyj1uGGiZg/0uzpJlBmKUHLV1y6japx0xRBGSALFlschs7cncVIsV6ms+q+l2t9QRpwQmRlpeEfIZKi2xTrPTigUC6bZOgm+jc4vzv6DxOy4pfnEX8yRhKvJqHLMk9QrkJZnnREyH/puPbfYoqcKI4DUlXPnqqUD/V7g0E2bdusEeg//Z9iI+loBPRzHpf4hMnSpLHrzW6RF+3JAF0iCELHLsrVnMw2bYNagjuYSVpypwV/Jo06AEylLqSkE+B7Ai10NiVpUhcWNgJFjL+GIfPVOxaN+aiAPSSQv+W7vSzLm/m8myX4OEOJKhVqq7VdsZNKg6xFvXt/ioWafplW/a9rX5kD9gITS7K5zUDYjBc2vQ19p3Pt8f2M+Dj6bUc1NGVYrFz3uAwD/okWjBpwoarvlX4zSRYa03reIR1hoeLaRWBAHhFSCG2SgluWJwcwSjbvOLUJNKYaIxZuBNmEwzKzhXCz6RXIUYOc5II47VE8q6ZL8l7EfbTU6EWB5r8mjHASsDGpXDwzcq/GuSohmmyqxtKtizjZ59trE2/YMSnkZ9HYreYz27FiwrwcfWcyZkvhjIwKFlU86ZuuC3WhjOaWfENdBGZRdhmJqy8Ct2c6K7bNMPLC1ePyic2p542PyLsVYJkPSFlGoeL+M3gbggXll+Wl6eqrVyiYXCL9t9Q3YZiiMJyhdk9DqTcPV73T3Q+1weCuN/s6Tt47iHFMdg39MHY+FOFAFlI5/ytAIN5r9s9ZZQBtGe/Cen4KTgaKeMt+lt/XKofT4uXDYXItewb0njzXOpM/31P5QPt5mYQ5gwy5Som8JeG2Y/zda3gRN9ZGahf8eDu1YqP7+OFM=
  template:
    metadata:
      name: wolweb-devices
      namespace: wolweb
