---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wolweb-devices
  namespace: wolweb
spec:
  encryptedData:
    devices.json: AgArvDePihkO4IVxd+AvBDT1+XNbMXXdw7OEeoumwrM3l8raiq/BhDrpVhawxqsBoUNssdRDYk+YiEpxi3Tvj8vpQFJ86+rRjB0V6SND024s/GAOv/JpKsu9ORp8ECNBMvsBBqsT2POFpbiW5hd6ckdV/11uz3wANSS8QoS3wHdiZUw5Occ1dVPW26fzkZ22u0BkDSM+pTt72MvewEpwitjcIySY5Aq/XdjDvhcXsxzJXOXzuDMlafGPFekYvvhNnj4UpNXif7Ot/CqQEQBN20lsbzwPsjqdQ0+JAuuHEMJFhu+GWLqcKy862PJT3WCL1kVNb3CtDnC/nYn3mcVKrtqKYkhXp8unE+8t0OBfhn9YLyg2wCHKi9ijZPbC4E+fNHWM4DPyaqJ+YehFZK1XgHDfkPiGug1dOG+qb0StnZ6gY1jaEXJUHCeD3Ehkq/r58echIvHtHGvzGkQCP/UJFZpeWA1ymNKRteU8NdQYPIgXWGqzIzSF18dZe/BwRf1wuO8hjBd942W2P0lf7hC21NCEeo1wkxpKE4TJRwFtBSWcYXh9ko6PqLrF3ZrhF2Ylq87KBLGLNTiSnXruyak831Cs2hywtU/vpAyjqfwKw6+683L+nhb36ooD4SMVPjoqrdnh6WzxtUNBiLwsu9O0C7QmwxZwed9jhhFW3a/23qSG+cwALgRC1p2Gp+VpfGQRxvkqFfdb987QdvoyBvmpuGfBNluuYcTuMAgJmjjTb4cvNCZbk/Z62KYneZqXZn9OzTx59QyKNTwm2g6p0qwCEOuNFBkNCB91CyJW5nK03ZgJ9rx34K1rTq7pGsSzqqAGrYjIMY1LZuofRXX6wccvkH5fgcFE9FTl4eCDmPLGWt/O4DekrqYf63l1+cF8dvkKU+8JSjc=
  template:
    metadata:
      name: wolweb-devices
      namespace: wolweb
