---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ubichill-secrets
  namespace: ubichill
spec:
  encryptedData:
    BETTER_AUTH_SECRET: AgA0BA23GgumSMYLET0t+jqxIWCRQRysYJ+1qZFMS3SEzHcpxyq9U0CXJM8+BnNmo43xlJ+HUF8QQVwAgfYsEWpZHPFCPWyPOXC1uaQbjSMqph5VQ0BUfx1NKUI1aihwP7FOrki3HICKvyJ2h3j2HxXGUHLncKyuv9wk/blZ+wxVcHI814cXpF1BCAV6H4h2QaZfU7JksG0LxDPSGTmVDACPMSOYuwmphfKhTaIPUIdlerqVD36OiAG9KbtJgdHUds7DC6h8HV0oxcl6AQzEuh3r6B3GCVQNcYrpjOSup6ZE7LWEQIclKMlFr/cDwlUW73aNBK4Uc+EM5Dxyz2Qn9MBcV7SmkkF8VAi/hnpRgZtRowQcxziRusimIfMoFCWy6R8//nqTRL50KuNHs1iqCu+4UH/Jhi7e2gJwWiP859Z+eUUHngVebDxhPAquUgL36A19EDG0SWimDK387aeegh78Ild0H2GX7H9s3GMNhy89C8SeztkFBszBtq0EGnIzcdjY8teFGGGnafMK+P+2Pl49aGLjyHsUdv+o8fo0Eby0ZlTClKTKeckVrE1VYph2v4BxQ9gkxiey+Qn0klwwagBUrRdoWRjVcu+s+iViL98oESwIrAFHwwm+CpW0iH1dclEwc/fO1ZRnT+T7vTLjEikOWSrd32Upz9Kr8YifmdOSJxU9nqdzdak5K61opTkjVZpeJQrMA+bUmjI40DE+1TjllCDRxGXwDuNGZrwFjuGBB/Qd5pZYfcHB1sCABA==
    RESEND_API_KEY: AgAVQX8rPuJ9bhMHFge68CZpFoh/gYiHSlbdkp2015cbK2WfMpMYR7+Pqq7kx/LP/PMp+TkDduatJ93BKrG1VHGgjLXmtprafAv1QQRBiQVMbQr71jMv+i4r0SLpsaHLxnPSBX4XFZotxb86a6UG8g9Fdemv22pKE4eOWuQB471D5/y8LQ0Aa+gxMQ07Lp2wsAqjH5aZYUg2NR/grISDBMgOvS1CTkKgmHnKd54Umg603jnqCJmqM4y7WQZltWnrvyKlS5IA0stlhpgeVrL7NkWuZPZzdHbL9W4pgtzgQ5SCfF05y5hSA/EDC+LD1LosQGeuTxqZJjJyVr1FA6M+YOew82wjtd9DufdihkbzlxOism6bvT2Vg/f1kkcU0DFB/8AOfS959Let3WNtalbWiPyWvhV3piJ1xX2M0IXnK8B0YKjveaOFFW/K7ZrNbubF6kpMMLpRZ3xXvec3usNU31TZudt9Ku/W11nEbxNYYlXbK/Ahqil/1KYs1DYLFNgoJWIL1vHEEFdvS75JgbcKgIyFBa44Bwkf0ML/fsQMm7kUbw0TVMIc7amkY05YK5nsqIsMOL/dDG/sHAKttCc4wuMwg2n/4lPau8WsBK8Mz6cSRCaqgKIjNyyaKK0Jn4YHQvgEQ9WeZSJ3NGROC9Vjt4vtsrXZVfFc5XChOlXpKyHwSNYM+7bwrqFKiCUro3XvEP/Mamx8FBogGYIJ5iVNZn8Wzcxww6xS8/KDlaD59sHUDQNctoM=
  template:
    metadata:
      name: ubichill-secrets
      namespace: ubichill
