apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: misskey
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:prototype-japanese-13
          env:
            - name: MEILI_ENV
              value: "production"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MEILISEARCH_MASTER_KEY
          ports:
            - name: http
              containerPort: 7700
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /meili_data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: meilisearch-data
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: misskey
spec:
  selector:
    app: meilisearch
  ports:
    - name: http
      port: 7700
      targetPort: http
  type: ClusterIP
