---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-misskey-credentials
  namespace: misskey
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgA5qr9e8o2YnUig+Xq8i7BRa44vZSnJcIgDk5T+F2DgN9yADAwuRKDHEemx4h1TCLT7eTMm802zbY8+DzLmBi2VcBcN3fEzNTKMfXm5G6Si+OCb4mUFard7s1JaApOS09+F/fKwvqQDbLHpA2samyzZiM5k4+QpN91l8zAJnRqIpgpU/EK28d7JSOPMABkX0uR648qJ7+EKCaUSBop145gCrAG89N7AoQxqCkORxtonJVi62bfD17YgabHcuORqb9Wgu8VjjNTKAaXCPLkEgtsS5RpYsqcvJVk68O/aUSmtEtYc+1vb8S+FBxoT1YP9UrNSN7JKgCcKis/Cz1q9qubienoTzv4vzgCSxuPD4SHTAwGRJqxUHRMv58fC/MLHYRD/Pz7tX5iN5bXjDTLZYht92UR1XjiVhq+P3V6RQY+p84wJ3KE3IOeAFKMvFSxo/9LB5wlFGh4VHac653+/hDTzM9vcSau26ZdH1GUoTD2l/n8PFCwc3lyBli6WcsfygUF+GW3ouvb0mxp4OuVXynMjj233zMWrHGLOm7+hzLnPf0BfbMJj3qS90yNHz+Ul6SBN+t3WVRlP4q9Y9+Wd0aFDCjnjfH7RiE7WdmaMzO9h7zZg/Zfp/jX2gB/2fA5P5s0dGHZjAVUOXCTNNuOIn8zx9ged5wlX1Nk1NmDtRJWlQyWoY83H/tpRGzHnCI3TlgbIhxsbLSk=
    MINIO_SECRET_KEY: AgApJpoD0yT2ovBg2GYMuvkY65wYHOS6xLeUL7vlgbXZgQkLB9elOB2CceThVnXz8g7DPOSarKGVOfVp2NjAtPAOW00To3Pz6qqxYVi3QXW+fBMYVRoXI/PccO/1egsTDSt0itglEQSyYFD/t+VCOCovJmPB1oEIuPScD8cMbR2lUGzDrimgAs3XBfafCjBbwXObWA2XU0yD6MYt3ybMdU2duxoDEZBG9FbV/wXQxS8uQk4teTP4wHaI2uNgO9R6sIQMwc0Wf0Fy3AC4ZvlNoUoGaGO2jbjew0DwAjg1jyhqN2geapi7e57o35ZAafyfRkCQy2qFGi1UHtp+xqsMyHVzRVk1B/R3bvRLn4zW8qcmYprVOj+PGOFJ13rPwo8JH2vFyKKhe2tDkjvvNGVc3kHPlHMlTDmZ2n+HnyEsW0nZ9vgO+LEasZL+nl1FDNeExwDJoJMn8T8Q/O7koZ0wJiAcHjXZ5MmOsU7Ie3IXg5t05RGlZBbeqYfoTE3Ufnmm6ikTF8XXJ/3jX5Ue1S13OUGH4EfHxY4b9nb0CyrAHSIopnqtV7s1zAQK+yOaNe+IVvqB7xt3GXDk10LG3ZnFvlb46NJM/fxPXA9QBf3ghUMxKjX/sfRrJV4jD3aDnzrGgc2fFYCrdzwEybMNCLRgsJWVgShtTqZme8oEZcMiO+Ix22BHZGoMUeB/hRh4JDzmSR4k0eabvzJvhRa0VA6W7vc=
  template:
    metadata:
      name: minio-misskey-credentials
      namespace: misskey
