---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-uploads
  namespace: misskey
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      initContainers:
        - name: config-generator
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              mkdir -p /misskey/.config
              cat > /misskey/.config/default.yml <<EOF
              url: https://mi.youkan.uk
              port: 3000
              db:
                host: $DB_HOST
                port: $DB_PORT
                db: $DB_NAME
                user: $DB_USER
                pass: $DB_PASS
              redis:
                host: $REDIS_HOST
                port: $REDIS_PORT
                pass: $REDIS_PASS
              meilisearch:
                host: $MEILISEARCH_HOST
                port: $MEILISEARCH_PORT
                apiKey: $MEILISEARCH_API_KEY
              id: $MISSKEY_ID
              allowedPrivateNetworks: []
              drive:
                storage: fs
                baseUrl: https://mi.youkan.uk/files
              EOF
          env:
            - name: DB_HOST
              value: misskey-postgresql
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: misskey
            - name: DB_USER
              value: misskey
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: POSTGRES_PASSWORD
            - name: REDIS_HOST
              value: misskey-redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: REDIS_PASSWORD
            - name: MEILISEARCH_HOST
              value: meilisearch
            - name: MEILISEARCH_PORT
              value: "7700"
            - name: MEILISEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MEILISEARCH_MASTER_KEY
            - name: MISSKEY_ID
              value: aidx
          volumeMounts:
            - name: config-volume
              mountPath: /misskey/.config
      containers:
        - name: misskey
          image: misskey/misskey:2026.1.0-alpha.0
          env:
            - name: NODE_ENV
              value: production
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: config-volume
              mountPath: /misskey/.config
            - name: uploads
              mountPath: /misskey/files
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: config-volume
          emptyDir: {}
        - name: uploads
          persistentVolumeClaim:
            claimName: misskey-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: misskey
  namespace: misskey
spec:
  type: ClusterIP
  selector:
    app: misskey
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: misskey
  namespace: misskey
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mi.youkan.uk
spec:
  ingressClassName: cloudflare
  rules:
    - host: mi.youkan.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: misskey
                port:
                  number: 3000
