apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-uploads
  namespace: misskey
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
        - name: misskey
          image: ghcr.io/misskey-dev/misskey:2024.3.1
          env:
            - name: NODE_ENV
              value: production
            - name: MISSKEY_URL
              value: "https://misskey.example.com"  # TODO: 実ドメインに変更
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: misskey-redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: REDIS_PASSWORD
            - name: MEILISEARCH_HOST
              value: meilisearch
            - name: MEILISEARCH_PORT
              value: "7700"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MEILISEARCH_MASTER_KEY
            - name: MISSKEY_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MISSKEY_SECRET_KEY
            - name: MISSKEY_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MISSKEY_SIGNING_KEY
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: POSTGRES_PASSWORD
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: uploads
              mountPath: /misskey/files
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: misskey-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: misskey
  namespace: misskey
spec:
  type: ClusterIP
  selector:
    app: misskey
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: misskey
  namespace: misskey
  annotations:
    external-dns.alpha.kubernetes.io/hostname: misskey.example.com
spec:
  ingressClassName: cloudflare
  rules:
    - host: misskey.example.com  # TODO: 実ドメインに変更
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: misskey
                port:
                  number: 3000
