apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
  namespace: misskey
data:
  default.yml: |
    url: https://mi.youkan.uk
    
    # ポート設定
    port: 3000
    
    # データベース設定
    db:
      host: misskey-postgresql
      port: 5432
      db: misskey
      user: misskey
      pass: $MISSKEY_DB_PASS
      
    # Redis設定
    redis:
      host: misskey-redis-master
      port: 6379
      pass: $MISSKEY_REDIS_PASS
    
    # Meilisearch設定
    meilisearch:
      host: meilisearch
      port: 7700
      ssl: false
      apiKey: $MISSKEY_MEILISEARCH_API_KEY
    
    # ID生成方式
    id: 'aidx'
    
    # その他の設定
    allowedPrivateNetworks: []
    
    # ファイルストレージ設定
    drive:
      storage: 'fs'
      baseUrl: https://mi.youkan.uk/files
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-uploads
  namespace: misskey
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey
  namespace: misskey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
        - name: misskey
          image: misskey/misskey:2026.1.0-alpha.0
          env:
            - name: NODE_ENV
              value: production
            # データベース設定（ConfigMap default.yml で参照）
            - name: MISSKEY_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: POSTGRES_PASSWORD
            # Redis設定（ConfigMap default.yml で参照）
            - name: MISSKEY_REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: REDIS_PASSWORD
            # Meilisearch設定（ConfigMap default.yml で参照）
            - name: MISSKEY_MEILISEARCH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: misskey-secrets
                  key: MEILISEARCH_MASTER_KEY
          ports:
            - name: http
              containerPort: 3000
          volumeMounts:
            - name: config
              mountPath: /misskey/.config
              readOnly: true
            - name: uploads
              mountPath: /misskey/files
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 4Gi
      volumes:
        - name: config
          configMap:
            name: misskey-config
        - name: uploads
          persistentVolumeClaim:
            claimName: misskey-uploads
---
apiVersion: v1
kind: Service
metadata:
  name: misskey
  namespace: misskey
spec:
  type: ClusterIP
  selector:
    app: misskey
  ports:
    - name: http
      port: 3000
      targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: misskey
  namespace: misskey
  annotations:
    external-dns.alpha.kubernetes.io/hostname: mi.youkan.uk
spec:
  ingressClassName: cloudflare
  rules:
    - host: mi.youkan.uk
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: misskey
                port:
                  number: 3000
