---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
spec:
  encryptedData:
    discord-webhook-url: AgDdXrhKrxxzZrytYtk8m9v8EG+uqPRhhiEcrsuBrw2VMFqrq7v7zDl3puIuM0ubHin7oWBMuN1k+7RFRLveMA3mOZfJDxBXBUS/AHagU8Gss0NcJup8nXOT4Pyi5m7s85JoAzZ2i2NElHtCNUm4p6PdUY9Dl1VAaM1tbJ3ntgu21aL4r97qNbUXkh6479FPx7fV/+Bxy7qnC22TghomkZ3mun+VMsnwi2sSrSPIMz5pEn4C5yBKUw3kRsZ7pdxiBFXTMHh4JM4K8WX3JqFtp/dvWxJyYoOOq9dx/hvaideeoK52v/ga7UT9E3He7AP2YRrjSOBjb6PEydNbgc+LfzpLWF0F9HKqzrFWM28OGB985WlAx1pTm08Gtl/RkNgFdJUz76aFD7tqp6oHM4KN0zxxUejdj6uVbToOcZ63AZDfQSe4dtPggfn/unrhioGvCmn9Cz/SDNd98kV6sPqiffXmQCHahuzuBtFkxduXU8pVEIGkcdv/OPAlRN4jdUwOKTbx9zQ0HsI8ynV4cmdUHQbARw14gxzRNOJqmCT5VLGVsWiDb1cUlM9yAzin1l1w+Qg//APpXfYzJiM77nxOpRyu+NaC0+qhcuiNgZ0ARRXpvJA1Xpv/Pt1yucvp03GWbfLH+5/vIfz/+RZHq2sMiqr8R0GhZJrcZuwTOhi3/aJca6FsaUfHTHzNo4unmxIXLz8Zmj9d8N2UjQ/D0sx4nmSsJ0thjEOE0JUnHjBud0422sOdOFBwVEGDrmulwSOkWK2IwiMRNAo/zlYElM5A4IvPXuXfOJgExkI6PPHvWlgnAechIBrFxt845qDZ0QiLeGBf1WKDePyai8e3dTiuCK0KoM6J00Cjk6Pp
  template:
    metadata:
      name: argocd-notifications-secret
      namespace: argocd
