---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: argocd-image-updater-git-creds
  namespace: argocd
spec:
  encryptedData:
    password: AgBnmCcdL7937zjGfaL9GHc4yPprIApKPomTMII8zT2rJkZBWeb3uc5DC3+Q4yARTAK3t5u990xZZ3ae2ykMMkXcJEEF2kl6f7WVDmu7fUOofxvWTIvfY7UUyNW4OlPSKMOqnZUogk7SmZxqoF2ahaX95I+uv0pNjUviMLmN4xDnFs/pYj7AVV43VQfVjmx83EPRZ5VhMxNlTGXt7PJbfd0pFfBnfDqRRFLqucaGfOPWm9vue32Ky2dyneEREY01ZNwP4U6Ql4REzcZI+R3FQ3Ra88D93ZefS1EAy+tL96kW+4D6V3HQlp6BTcbBdvUu3taw3lqV844MVuInPRf+jN8r31kMwfta5o1+gOHe1r+ZPnGqZTjC93m/0gRcpY6VHI4EeEDrQDAor5n/0HbW01zmIYLTEFT8RkTt0PTL/QJMtwEj1+JfzivNzY3N+Y8+LsH8ofKrUAcwZaRyy2xw68MnxiNe02wriwX/wh/8atx186+EBvFCudOy3ytbvh0Yn95rcmUGEZIt21kcj+n9ZaqImGifewWIM5lxv1dwW3BK88dAmWtrf+SOf8lbM+B9LWDTxQegLrPWF0KKKzSst+wAcfDhlPeRimBBGArPy0LKFzRKXEL0OGMtm4PVMGJwOLY97JkR4HbQXI7wrh1QnYb+JylsoMejjKS6k6t5ZSjmwOyxfPhOxyj9pRrgOIRGmpz7+x8GK8byMKd3vl/8+Aj14Vwz5wfO9Op8C7HczGhP0wQDAa2Iaqxj
    username: AgCZy5H8hgbf9i5K76uSEhsKyR6duE67pugZb1eq+YAIUsOVBNUriU2DOV5PjGITvrLdKIaarAM4t69NaOFWmyPEtub1iEKlW1yfIjhMzA5HNZ4hJAyTP4CQT2ToDm8JB3/X2Kmerp3jqLDFKbZfU+INicbLuwhan1QsKBvnl+n62fuCza8E3CxTaJEMlrapiclLPkaCRhxQMOEDNZ4Lc2x2wmM53jivWidnfS9RzWGkJfc5+lMYKYj4pwR4kcOghaWcZBmOsiRa0IKeXqUeUn8FcUknpglt6ZpvVHOVIYtQ5AubyFyRSHebP+1U+bjMhG7e4L+HvvCeUtLDj3MNgrwn8PkfKzew58yQ6yM+OgCOUNroWnPpqPUHi6bGYsGM8ALpxM8UOrWTje1LjQ2MhwJolU3eTO6U4FFq3SY9riozEz1x/7Tk1l4IPYQcHPymoiYc6/bIdmIxI9M9HkM4JVe8uWhHSSqXRzCBHGRVzGLBQf8MArPOCgLCCPCmezechuPUxd8zZfSDmoFrB9/xoNXYl078Je1OlaoLwl7lCz9FLPpqfszxOFHcnObS2BPN2zMsXxe+403nFzWZJYwwOqp1dTctItX8XRyzNL9lcMDP9IkKNYNr8R4lrLDYIcAOy3KTytGkFN5dRcvoDr3hSMS1LOxa+5R7Yczw75+2Cb+Etm5iXmiyRvXWORAUNOIkHb5x/NbyS7GGaFRKUA==
  template:
    metadata:
      name: argocd-image-updater-git-creds
      namespace: argocd
